[Icon Theme]
Name=ZoroIcons
Comment=Zoro Linux icon theme based on Papirus, recoloured to Zoro palette
Inherits=Papirus-Dark,hicolor
Example=folder

# Directory list
Directories=16x16/actions,16x16/apps,16x16/categories,16x16/devices,16x16/emblems,16x16/mimetypes,16x16/places,16x16/status,22x22/actions,22x22/apps,22x22/categories,22x22/devices,22x22/emblems,22x22/mimetypes,22x22/places,22x22/status,24x24/actions,24x24/apps,24x24/places,32x32/actions,32x32/apps,32x32/categories,32x32/devices,32x32/places,48x48/actions,48x48/apps,48x48/categories,48x48/devices,48x48/places,64x64/apps,64x64/places,symbolic/actions,symbolic/apps,symbolic/categories,symbolic/devices,symbolic/emblems,symbolic/mimetypes,symbolic/places,symbolic/status

[16x16/actions]
Size=16
Type=Fixed

[16x16/apps]
Size=16
Type=Fixed

[16x16/categories]
Size=16
Type=Fixed

[16x16/devices]
Size=16
Type=Fixed

[16x16/emblems]
Size=16
Type=Fixed

[16x16/mimetypes]
Size=16
Type=Fixed

[16x16/places]
Size=16
Type=Fixed

[16x16/status]
Size=16
Type=Fixed

[22x22/actions]
Size=22
Type=Fixed

[22x22/apps]
Size=22
Type=Fixed

[22x22/categories]
Size=22
Type=Fixed

[22x22/devices]
Size=22
Type=Fixed

[22x22/emblems]
Size=22
Type=Fixed

[22x22/mimetypes]
Size=22
Type=Fixed

[22x22/places]
Size=22
Type=Fixed

[22x22/status]
Size=22
Type=Fixed

[24x24/actions]
Size=24
Type=Fixed

[24x24/apps]
Size=24
Type=Fixed

[24x24/places]
Size=24
Type=Fixed

[32x32/actions]
Size=32
Type=Fixed

[32x32/apps]
Size=32
Type=Fixed

[32x32/categories]
Size=32
Type=Fixed

[32x32/devices]
Size=32
Type=Fixed

[32x32/places]
Size=32
Type=Fixed

[48x48/actions]
Size=48
Type=Fixed

[48x48/apps]
Size=48
Type=Fixed

[48x48/categories]
Size=48
Type=Fixed

[48x48/devices]
Size=48
Type=Fixed

[48x48/places]
Size=48
Type=Fixed

[64x64/apps]
Size=64
Type=Fixed

[64x64/places]
Size=64
Type=Fixed

[symbolic/actions]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/apps]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/categories]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/devices]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/emblems]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/mimetypes]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/places]
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/status]
Size=16
MinSize=8
MaxSize=512
Type=Scalable
